config/routes.rb
MicTest::Application.routes.draw do
  root to: 'users#new'
  match 'question' => 'questions#index'
  match 'foo' => 'questions#foo'
  resources :questions do
    member do
      resources :answers, only: [ :new, :create ]
    end
  end
  resources :users, only: [ :new, :create ] do
    collection do
      get :success
    end
  end
  resource :sessions, only: [ :new, :create, :destroy ]
  get "admin" => "admin/sessions#new"
  namespace :admin do
    resources :questions
    resources :variants, except: [ :show ]
    resource :sessions, only: [ :new, :create, :destroy ]
    resources :users, only: :index do
      member do
        resources :answers, only: :index
      end
    end
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :login, :password

  validates :login, presence: true
  validates :password, presence: true
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :text,
                  :question_id,
                  :user_id,
                  :variant_id

  belongs_to :question
  belongs_to :user
  belongs_to :variant

  validates :question_id, presence: true
  validates :user_id, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  next_record_order :id
  attr_accessible :answer,
                  :text,
                  :right_answer_id

  has_many :answers
  has_many :variants

  validates :text, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :card_num, :district, :fio

  has_many :answers

  validates :card_num, presence: :true, length: { maximum: 3 }, uniqueness: true
  validates :district, presence: true
  validates :fio, presence: true, length: { minimum: 2 }
end

app/models/variant.rb
class Variant < ActiveRecord::Base
  attr_accessible :text, :question_id

  has_many :answers

  belongs_to :question
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::ApplicationController
  def index
    @questions = Question.all
    @answers = []
    @questions.each do |question|
      answer = question.answers.where("user_id = ?", params[:id]).first
      if answer
        @answers << answer
      end
    end
    @answers = AnswerDecorator.decorate_collection @answers
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  def new
    if admin_signed_in?
      redirect_to admin_users_path
    else
      @admin = Admin.new
    end
  end

  def create
    @admin = Admin.find_by_login params[:admin][:login]
    if @admin && authenticate_admin?(@admin, params[:admin][:password])
      admin_sign_in @admin
      redirect_to admin_users_path, flash: :success
    else
      @admin = Admin.new params[:admin]
      flash[:notice] = t('wrong_login')
      render action: :new
    end
  end

  def destroy
    admin_sign_out
    redirect_to :root, flash: :success
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    @users = User.all.reverse
  end
end

app/controllers/admin/variants_controller.rb
class Admin::VariantsController < Admin::ApplicationController
  def new
    @variant = Variant.new
  end

  def create
    @variant = Variant.new params[:variant]
    if @variant.save
      redirect_to admin_questions_path, flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def update
    @variant = Variant.find params[:id]
    if @variant.update_attributes params[:variant]
      redirect_to admin_questions_path, flash: :success
    else
      render action: :edit, flash: :error
    end
  end

  def edit
    @variant = Variant.find params[:id]
  end

  def index
    @variants = Variant.all
  end

  def destroy
    @variant = Variant.destroy
    @variant.destroy
    redirect_to :root
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    unless params[:id]
      redirect_to success_users_path
    end
    @question = Question.find params[:id]
    @answer = Answer.new
  end

  def create
    @answer = Answer.new params[:answer]
    if @answer.save
      if @answer.question.next
        redirect_to new_answer_path(@answer.question.next), flash: :success
      else
        redirect_to success_users_path
      end
    else
      render action: :new, flash: :error
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AuthHelper
  protect_from_forgery
  $user_id
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_card_num params[:user][:card_num]
    if @user && authenticate_user?(@user, params[:user][:fio])
      user_sign_in @user
      redirect_to new_answer_path(Question.first), flash: :success
    else
      @user = User.new params[:user]
      flash[:notice] = t('.wrong_login')
      render action: :new
    end
  end

  def destroy
    user_sign_out
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    unless current_user
      @user = User.new
    else
      redirect_to new_answer_path(Question.first)
    end
  end

  def create
    @user = User.new params[:user]
    if @user.save
      user_sign_in @user
      redirect_to new_answer_path(Question.first), flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def success
  end
end

app/helpers/admin/answers_helper.rb
module Admin::AnswersHelper
  def points(answers)
    points = 0
    answers.each do |answer|
      if answer.check == :right
        points += 1
      end
    end
    points
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin/session_helper.rb
module Admin::SessionHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin/variants_helper.rb
module Admin::VariantsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include AuthHelper

  def copyright_notice_year_range(start_year)
    start_year = start_year.to_i
    current_year = Time.new.year
    if current_year > start_year && start_year > 2000
      "#{start_year} - #{current_year}"
    elsif start_year > 2000
      "#{start_year}"
    else
      "#{current_year}"
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
  include MICDistricts
end

app/views/admin/variants/_form.html.haml
= simple_form_for @variant, url: { controller: 'admin/variants', action: action }, html: { class: 'form-horizontal' } do |f|
  = f.association :question, value_method: :id, label_method: :text
  = f.input :text
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = link_to t('.cancel', default: t("helpers.links.cancel")), admin_variants_path, class: 'btn'

app/views/admin/variants/edit.html.haml
- model_class = Variant
.page-header
  %h1=t '.title'
= render partial: "form", locals: { action: :update }

app/views/admin/variants/index.html.haml
- model_class = Variant
.page-header
  %h1=t '.title', default: model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:question_id)
      %th= model_class.human_attribute_name(:text)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', default: t("helpers.actions")
  %tbody
    - @variants.each do |variant|
      %tr
        %td= link_to variant.id, admin_variant_path(variant)
        %td= variant.question_id
        %td= variant.text
        %td=l variant.created_at
        %td
          = link_to t('.edit', default: t("helpers.links.edit")), edit_admin_variant_path(variant), class: 'btn btn-mini'
          = link_to t('.destroy', default: t("helpers.links.destroy")), admin_variant_path(variant), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-mini btn-danger'

app/views/admin/variants/new.html.haml
- model_class = Variant
.page-header
  %h1=t '.title'
= render partial: "form", locals: { action: :create }