config/routes.rb
MicTest::Application.routes.draw do
  root to: 'users#new'
  match 'question' => 'questions#index'
  match 'foo' => 'questions#foo'
  resources :questions do
    member do
      resources :answers, only: [ :new, :create ]
    end
  end
  resources :users, only: [ :new, :create ] do
    collection do
      get :success
    end
  end
  resource :sessions, only: [ :new, :create, :destroy ]
  get "admin" => "admin/sessions#new"
  namespace :admin do
    resources :questions
    resources :variants, except: [ :show ]
    resource :sessions, only: [ :new, :create, :destroy ]
    resources :users, only: :index do
      member do
        resources :answers, only: :index
      end
    end
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :login, :password

  validates :login, presence: true
  validates :password, presence: true
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :text,
                  :question_id,
                  :user_id,
                  :variant_id

  belongs_to :question
  belongs_to :user
  belongs_to :variant

  validates :question_id, presence: true
  validates :user_id, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  next_record_order :id
  attr_accessible :answer,
                  :text,
                  :right_answer_id

  has_many :answers
  has_many :variants

  validates :text, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :card_num, :district, :fio

  has_many :answers

  validates :card_num, presence: :true, length: { maximum: 3 }, uniqueness: true
  validates :district, presence: true
  validates :fio, presence: true, length: { minimum: 2 }
end

app/models/variant.rb
class Variant < ActiveRecord::Base
  attr_accessible :text, :question_id

  has_many :answers

  belongs_to :question
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    @users = User.all.reverse
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    unless params[:id]
      redirect_to success_users_path
    end
    @question = Question.find params[:id]
    @answer = Answer.new
  end

  def create
    @answer = Answer.new params[:answer]
    if @answer.save
      if @answer.question.next
        redirect_to new_answer_path(@answer.question.next), flash: :success
      else
        redirect_to success_users_path
      end
    else
      render action: :new, flash: :error
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AuthHelper
  protect_from_forgery
  $user_id
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_card_num params[:user][:card_num]
    if @user && authenticate_user?(@user, params[:user][:fio])
      user_sign_in @user
      redirect_to new_answer_path(Question.first), flash: :success
    else
      @user = User.new params[:user]
      flash[:notice] = t('.wrong_login')
      render action: :new
    end
  end

  def destroy
    user_sign_out
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    unless current_user
      @user = User.new
    else
      redirect_to new_answer_path(Question.first)
    end
  end

  def create
    @user = User.new params[:user]
    if @user.save
      user_sign_in @user
      redirect_to new_answer_path(Question.first), flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def success
  end
end

app/helpers/admin/answers_helper.rb
module Admin::AnswersHelper
  def points(answers)
    points = 0
    answers.each do |answer|
      if answer.check == :right
        points += 1
      end
    end
    points
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin/session_helper.rb
module Admin::SessionHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin/variants_helper.rb
module Admin::VariantsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include AuthHelper

  def copyright_notice_year_range(start_year)
    start_year = start_year.to_i
    current_year = Time.new.year
    if current_year > start_year && start_year > 2000
      "#{start_year} - #{current_year}"
    elsif start_year > 2000
      "#{start_year}"
    else
      "#{current_year}"
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
  include MICDistricts
end

app/views/layouts/_footer.html.haml
.row-fluid
  .span4
    .logo.mic
      %a{ href: "http://ulmic.ru" }
.row-fluid
  %hr
  .offset2
  .span5
    %a &copy
    = copyright_notice_year_range(2012)
    %a{ href: "http://ulmic.ru" }
      = t('.youth_initiative_centre')
    %br
    %small
      = t('.this_project_develop_by_programmers_of_ulmic')
    %br
    %small
      %a{ href: "http://github.com/ulmic/mic_test" }
        = t('.this_project_on_the_Github')
  - if user_signed_in?
    .span2
      = link_to t('sign_out'), sessions_path, method: :delete, class: 'btn btn-danger'

app/views/layouts/admin.html.haml
<!DOCTYPE html>
%html
%head
  %title
    = t('.mic_test')
  = stylesheet_link_tag    "application", media: "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body
  .row
    .offset2.span8
      = render 'layouts/admin/navbar'
      = flash_messages :close
      = yield
      = render 'layouts/footer'

app/views/layouts/admin/_navbar.html.haml
%ul.list-inline
  %li
    = link_to t('.questions'), admin_questions_path
  %li
    = link_to t('.users'), admin_users_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('.mic_test')%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class = "row">
    <div class = "offset2 span8">
      <%= flash_messages :close %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </div>
</body>
</html>